7 backend create api/ingredients endpoint post option
SoftwareEngineeringGroup3-3/recipe-app-backend pull request #29
Opened 2022-03-17 22:30 UTC by Nomi

Finished.

2022-03-17 23:40 UTC, MateuszWojtynski requested changes

2022-03-17 23:40 UTC, MateuszWojtynski commented on server/endpoints/ingredients.js
> +    id: {required: false, type: 'integer'},
Remove 'id', as it will be assigned by the server, not frontend.

2022-03-17 23:40 UTC, MateuszWojtynski commented on server/endpoints/ingredients.js
> +        //const data = this.parseAndValidate(req.body, ingredientClassFormat, false); //causes wrong error numbers to be returned. Replaced by simple parse in the following line:
this HAS TO work, try `this.parseAndValidate(req.body, ingredientClassFormat, true);`

2022-03-17 23:40 UTC, MateuszWojtynski commented on server/endpoints/ingredients.js
> +    photo: { required: false, type: 'string'}
add lambda to photo: `lambda: () => { return true; }`
or implement some validator to check if the given string is for example an url

2022-03-17 23:40 UTC, MateuszWojtynski commented on server/endpoints/ingredients.js
> +        }
Remove this part, use functions that are already written (`parseAndValidate` in this case) as they have to work for everything.
If not then something is wrong.

2022-03-17 23:40 UTC, MateuszWojtynski commented on server/endpoints/ingredients.js
> +        //ingredient.id=data.id; //Is this line needed? The API specificatio`n seems to suggest so, yet so it did for Registration but we removed this line from that.
We will not need `ID` as it will be assigned automatically by the database when new ingredient will be inserted.

2022-03-17 23:42 UTC, MateuszWojtynski commented on server/endpoints/ingredients.js
> +        //const data = this.parseAndValidate(req.body, ingredientClassFormat, false); //causes wrong error numbers to be returned. Replaced by simple parse in the following line:
This will work after removing `id` and assigning `lambda` in `ingredientClassFormat`

2022-03-18 00:28 UTC, Nomi commented on server/endpoints/ingredients.js
> +    photo: { required: false, type: 'string'}
Originally your ingredientFormat inside the ingredient class itself had (still has) lambda: ()=>{} so I just removed it. Turns out you need to return true inside those.

2022-03-18 00:28 UTC, Nomi commented on server/endpoints/ingredients.js
> +        }
IIRC, they work but give the wrong error code.

2022-03-18 00:30 UTC, Nomi commented on server/endpoints/ingredients.js
> +        //const data = this.parseAndValidate(req.body, ingredientClassFormat, false); //causes wrong error numbers to be returned. Replaced by simple parse in the following line:
Refer to my comment on the other part.

2022-03-18 00:33 UTC, Nomi commented on server/endpoints/ingredients.js
> +    id: {required: false, type: 'integer'},
We're sent the id according to the api. Kept this in here in order to allow quick patch-in if needed. Can remove of course, but get back to me.

2022-03-18 00:36 UTC, Nomi commented on server/endpoints/ingredients.js
> +        //ingredient.id=data.id; //Is this line needed? The API specificatio`n seems to suggest so, yet so it did for Registration but we removed this line from that.
Okay, so I will be moving ahead with removing ID parts.

2022-03-18 00:37 UTC, MateuszWojtynski commented on server/endpoints/ingredients.js
> +    id: {required: false, type: 'integer'},
we can leave it like this, but you have to add `lambda`.
If you do not want to add real validator just add `lambda; () => { return true; }`

2022-03-18 00:39 UTC, MateuszWojtynski commented on server/endpoints/ingredients.js
> +        //const data = this.parseAndValidate(req.body, ingredientClassFormat, false); //causes wrong error numbers to be returned. Replaced by simple parse in the following line:
Okay, then it is needed to check if they always return 403 code for validation error in API. If yes, then `validateFormat` function shall be changed

2022-03-18 00:40 UTC, Nomi commented on server/endpoints/ingredients.js
> +    id: {required: false, type: 'integer'},
But I don't really see any validators being required for now. Maybe uniqueness, but tbh that either needs to be checked at the frontend or, as a sane person would do it, do it in the backend as we do.

Also, I don't really know how to validate photo. Probably as a URL but since it's an optional field, I didn't implement any yet.

2022-03-18 00:42 UTC, MateuszWojtynski commented on server/endpoints/ingredients.js
> +        //const data = this.parseAndValidate(req.body, ingredientClassFormat, false); //causes wrong error numbers to be returned. Replaced by simple parse in the following line:
NOTE: API is inconsistent when it comes to the validate error code, so for now leave it as 400.

2022-03-18 00:46 UTC, Nomi commented on server/endpoints/ingredients.js
> +        //const data = this.parseAndValidate(req.body, ingredientClassFormat, false); //causes wrong error numbers to be returned. Replaced by simple parse in the following line:
So, should I change it to use the parseAndValidate function? Or do we not take a risk for now and change it later with an issue open and pending till we get a reply from the other group?

2022-03-18 00:53 UTC, MateuszWojtynski commented on server/endpoints/ingredients.js
> +    id: {required: false, type: 'integer'},
You can for example check if a string ends with `.jpg` or `.png`

2022-03-18 00:55 UTC, Nomi commented
Agreed upon changes from this review have been made.

2022-03-18 00:56 UTC, MateuszWojtynski commented on server/endpoints/ingredients.js
> +        //const data = this.parseAndValidate(req.body, ingredientClassFormat, false); //causes wrong error numbers to be returned. Replaced by simple parse in the following line:
change it to parseAndValidate, to keep consistency in our code

2022-03-18 00:57 UTC, MateuszWojtynski commented on server/endpoints/ingredients.js
> +    photo: { required: false, type: 'string'}
You do not need to add lambda, the validator function will cope with such case, but it looks better when everything is in place XD

2022-03-18 00:58 UTC, MateuszWojtynski commented on server/endpoints/ingredients.js
> +    photo: { required: false, type: 'string'}
Also people that will read the code after yourself, will have a better view of what is happening if all fields will have matching parameters

2022-03-18 01:02 UTC, MateuszWojtynski requested changes

2022-03-18 01:02 UTC, MateuszWojtynski commented on server/endpoints/ingredients.js
> +        const data = this.parseAndValidate(req.body, ingredientClassFormat, false);
Why aren't you enforcing `required`? This way required parameter will not be treated as required

2022-03-18 01:24 UTC, MateuszWojtynski requested changes

2022-03-18 01:24 UTC, MateuszWojtynski commented on server/endpoints/ingredients.js
> +    id: {required: false, type: 'integer', lambda: () => { return true; }},
Change `integer` to `number`

2022-03-18 01:26 UTC, MateuszWojtynski commented
Okay I guess now it works :)

2022-03-18 01:27 UTC, MateuszWojtynski approved these changes

2022-03-18 01:27 UTC, Nomi commented
> Okay I guess now it works :)

BTW I named the last commit in reverse :P

2022-03-18 01:28 UTC, Nomi commented on server/endpoints/ingredients.js
> +    id: {required: false, type: 'number', lambda: () => { return true; }},
changed from integer to number. Commit title is the other way round.

2022-03-18 01:28 UTC, merged