40 backend create apiingredientsnext endpoint get option
SoftwareEngineeringGroup3-3/recipe-app-backend pull request #50
Opened 2022-04-02 18:07 UTC by Nomi

2022-04-02 18:08 UTC, Nomi commented
Need feedback. Check commented out parts.

2022-04-02 20:34 UTC, MateuszWojtynski requested changes

2022-04-02 20:34 UTC, MateuszWojtynski commented on server/endpoints/ingredients-next.js
> +        }
This endpoint should work for casual user, not only admin.

2022-04-02 20:34 UTC, MateuszWojtynski commented on server/endpoints/ingredients-next.js
> +        // let recipesWithPartialIngredients=req.database.prepare(`SELECT recipe_ingredients as RI FROM recipes WHERE ${queryPart.join(' AND ')} ORDER BY LENGTH(recipe_ingredients) DESC LIMIT 3 `).al
Why `LENGTH` and not `COUNT`?

2022-04-02 20:34 UTC, MateuszWojtynski commented on server/endpoints/ingredients-next.js
> +        // let recipesWithPartialIngredients=req.database.prepare(`SELECT recipe_ingredients as RI FROM recipes WHERE ${queryPart.join(' AND ')} ORDER BY LENGTH(recipe_ingredients) DESC LIMIT 3 `).al
In general, this is what I thought of, so we just need to make it work and gonna be OK.

2022-04-02 20:34 UTC, MateuszWojtynski commented on server/endpoints/ingredients-next.js
> +        ////especially considering that some SQLite functions like LENGTH() aren't working.
We discussed this topic at the beginning of the project, and we chose simplicity over performance, so as long as we can, let's stick to this

2022-04-02 21:36 UTC, Nomi commented on server/endpoints/ingredients-next.js
> +        // let recipesWithPartialIngredients=req.database.prepare(`SELECT recipe_ingredients as RI FROM recipes WHERE ${queryPart.join(' AND ')} ORDER BY LENGTH(recipe_ingredients) DESC LIMIT 3 `).al
Because length, in the manner I tried to use here, retrieves the length of each member of the column. So, basically it'd find the biggest recipe so that we don't run out of ingredients early.

Nothing important tbh.

2022-04-02 21:37 UTC, Nomi commented on server/endpoints/ingredients-next.js
> +        // let recipesWithPartialIngredients=req.database.prepare(`SELECT recipe_ingredients as RI FROM recipes WHERE ${queryPart.join(' AND ')} ORDER BY LENGTH(recipe_ingredients) DESC LIMIT 3 `).al
Well, let's discuss it tomorrow then.

2022-04-02 21:37 UTC, Nomi commented on server/endpoints/ingredients-next.js
> +        ////especially considering that some SQLite functions like LENGTH() aren't working.
Okay, we'll stick with this approach. But you'll have to help me a bit anyway :3.

2022-04-02 21:43 UTC, MateuszWojtynski commented on server/endpoints/ingredients-next.js
> +        // let recipesWithPartialIngredients=req.database.prepare(`SELECT recipe_ingredients as RI FROM recipes WHERE ${queryPart.join(' AND ')} ORDER BY LENGTH(recipe_ingredients) DESC LIMIT 3 `).al
OK, I understand, so maybe it would be just enough if we filter all recipes that have n+1 ingredients where n is the number of ingredients already provided? Because if there is a request for this endpoint we assume that the user still wants to pick ingredients, not finish searching (so recipes that contain only those ingredients provided so far, nothing more, shouldn't be included)

2022-04-26 22:31 UTC, MateuszWojtynski requested changes

2022-04-26 22:31 UTC, MateuszWojtynski commented on server/endpoints/ingredients-next.js
> +const { data } = require('cheerio/lib/api/attributes');
Is this needed?

2022-04-26 22:31 UTC, MateuszWojtynski commented on server/config.json
>          "/api/recipes/:id" : "./endpoints/recipes.js",
Remove `/api`

2022-05-18 15:46 UTC, merged