Completed /api/user/{id} - PUT.
SoftwareEngineeringGroup3-3/recipe-app-backend pull request #52
Opened 2022-04-02 21:04 UTC by Nomi

2022-04-02 21:08 UTC, Nomi commented
The tests failing is normal because I had to resolve conflicts for config.json manually and hence it's missing some files that should be there on the main branch but not here.

2022-04-02 21:47 UTC, MateuszWojtynski commented
> The tests failing is normal because I had to resolve conflicts for config.json manually and hence it's missing some files that should be there on the main branch but not here. So, the program isn't even running.

What do you mean by some missing files that should be there on the main branch but not here? If you want some files from main to appear also on this branch run `git pull origin main` from VS Code on this branch

2022-04-02 21:49 UTC, MateuszWojtynski requested changes

2022-04-02 21:49 UTC, MateuszWojtynski commented on server/config.json
> +        "/api/users/:id": ".endpoints/users/:id"
Should be `"./endpoints/users.js"` I guess

2022-04-02 21:49 UTC, MateuszWojtynski commented on server/endpoints/user.js
> +const { ApiObject, ApiError } = require ('../apiobject.js');
FILE NAME - change to `users` to keep consistency with endpoint name

2022-04-02 23:27 UTC, Nomi commented on server/config.json
> +        "/api/users/:id": ".endpoints/users/:id"
yes, my bad.

2022-04-02 23:28 UTC, Nomi commented on server/endpoints/user.js
> +const { ApiObject, ApiError } = require ('../apiobject.js');
okay

2022-04-02 23:28 UTC, Nomi commented
> > The tests failing is normal because I had to resolve conflicts for config.json manually and hence it's missing some files that should be there on the main branch but not here. So, the program isn't even running.
> 
> What do you mean by some missing files that should be there on the main branch but not here? If you want some files from main to appear also on this branch run `git pull origin main` from VS Code on this branch

Nothing, I was being stupid.

2022-04-05 23:12 UTC, MateuszWojtynski requested changes

2022-04-05 23:12 UTC, MateuszWojtynski commented on server/endpoints/users.js
> +};
From API docs, this is not needed. Only ID, which is passed as a parameter, so we don't have to (and definitely cannot require) those fields.

2022-04-05 23:12 UTC, MateuszWojtynski commented on server/endpoints/users.js
> +};
If you want to treat this as a `userPutValidation` then remove `isAdmin` as we probably won't change users permissions after creation and change `password` and `username` required to `false` because user may only want to change one field.

2022-04-05 23:12 UTC, MateuszWojtynski commented on server/endpoints/users.js
> +        }
Due to the above comment, what if `newData.username == undefined`?

2022-04-05 23:12 UTC, MateuszWojtynski commented on server/endpoints/users.js
> +        userData.password=await hashPassword(newData.password);
same as above

2022-04-05 23:12 UTC, MateuszWojtynski commented on server/endpoints/users.js
> +        }
Same as above. 

If at some point we decide to add such feature, it will be easy, so remove it for now.

2022-04-06 13:14 UTC, Nomi commented on server/endpoints/users.js
> +};
Resolved in the upcoming commit.

2022-04-06 13:14 UTC, Nomi commented on server/endpoints/users.js
> +        }
Resolved in upcoming commit.

2022-04-06 13:15 UTC, Nomi commented on server/endpoints/users.js
> +        userData.password=await hashPassword(newData.password);
Resolved in the upcoming commit (will commit in ~1 minute)

2022-04-06 13:15 UTC, Nomi commented on server/endpoints/users.js
> +        }
Resolved in upcoming commit. (ETA 1 Minute)

2022-04-06 14:32 UTC, merged