Adjusted tests to be in line with the specs.
SoftwareEngineeringGroup3-3/recipe-app-backend pull request #62
Opened 2022-05-22 22:18 UTC by Nomi

Though I had to take some liberties with things that weren't specified.

2022-05-22 22:20 UTC, Nomi commented
The failed tests are due to API inconsitencies. I checked, but the reviewer is welcome to double check :).

2022-05-30 20:39 UTC, MateuszWojtynski requested changes
I hope that the rest is ok XD

2022-05-30 20:39 UTC, MateuszWojtynski commented on server/templates/user.js
> +        // this.bindProperty('savedRecipes', 'user_savedRecipes'); //A separate table now? Commenting for now. Will remove or uncomment when confirmed.
This is the same, can be removed.

2022-05-30 20:57 UTC, MateuszWojtynski approved these changes

2022-05-30 20:57 UTC, merged